spring:
  http:
    encoding: utf-8

security:
  oauth2:
    client:
      clientId: accounting
      clientSecret: ocfs
      accessTokenUri: http://localhost:5000/auth/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      tokenInfoUri: http://localhost:5000/auth/oauth/token
      userInfoUri: http://localhost:5000/auth/users/current

spring:
  data:
    mongodb:
      host: localhost
      username: user
      password: ocfs
      database: accounting
      port: 27018

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  context-path: /accounting
  port: 8080
